maritimeTool/urls.py
from django.urls import reverse
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()




app_name = 'scrape'
urlpatterns = [
    path('', include('scrape.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

scrape/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import static
from django.urls.conf import re_path
from . import  views
from scrape.views import filter, blanksailing


app_name = 'scrape'


urlpatterns = [

    path('', views.IndexView.as_view(), name='index'),
    path('blanksailing/',blanksailing, name='blanksailing'),
#    path('blanksailing/',views.BlankSailingView.as_view(), name='blanksailing'),
    path('filter/<slug:slug>',filter,name='filter'),
#    path('<int:yr>/filter/',views.filter,name='filter'),
#    path(r'filter/(?P<yyyy:year>)/(?P<month>)/$',views.filter),
    path('vesselroute/',views.VesselRouteView.as_view(), name='vesselroute'),
]
#+ static(settings.STATIC_URL,document_root='../Maritime_Web_Tool/scrape/static')

scrape/models.py
import os
from datetime import datetime
from typing import Any
from django.conf.urls import static
from django.db import models
from django.utils.translation import gettext_lazy as _
import calendar


monthsNUM = [i for i in range(1,13)]
monthsNAME = [calendar.month_name[month_idx] for month_idx in range(1, 13)]
currentYear = datetime.now().year



MONTH_DICT = dict(zip(monthsNUM,monthsNAME))
MONTH_LIST = list(zip(monthsNUM,monthsNAME))

YEARS = [
    ('2021','2021'),('2020','2020')
]

CARRIER_LIST = [
        ('hlc','Hapag'),
        ('cma', 'CMA'),
        ('maeu', 'Maersk'),
        ('msc', 'MSC')
    ]




class Carrier(models.Model):
    name = models.CharField(max_length=50)
    code = models.CharField(max_length=5)
    bool = models.BooleanField()
    def __str__(self,code,bool) -> str:
        return super().__str__(self,code, bool)

    def list():
        list = set(CARRIER_LIST)
        return list


# class BSFilter(models.Model):
#     carriers = models.CharField(max_length=20)
#     month = models.IntegerField()
#     year = models.IntegerField(choices=[(2020,'2020'),(2021,'2021')])
#     bool = models.BooleanField(blank=False,null=False)

#     MONTH_LIST = MONTH_LIST
#     def whatMonth(MONTH_LIST):
#         return MONTH_LIST.objects.all()
#     YEAR_CHOICES = ['2020','2021']
#     def whatyear(YEAR_CHOICES):
#         return YEAR_CHOICES.objects.all()


# class FourDigitYearConverter:
#     regex = '[0-9]{4}'
#     def to_python(self, value):
#         return int(value)
#     def to_url(self, value):
#         return '%04d' % value

scrape/forms.py
from datetime import datetime
from django.template.loader import render_to_string
from django import forms
from django.db import models
from django.db.models.aggregates import Variance
from django.db.models.lookups import Range, YearLte
from django.forms import fields, widgets
from django.forms.models import model_to_dict
from django.utils.regex_helper import contains
from django.utils.translation import activate, gettext_lazy as _
from datetime import date
from django.forms.widgets import HiddenInput, Widget

from .models import CARRIER_LIST, YEARS, MONTH_LIST, MONTH_DICT





class BSfilterForm(forms.Form):

    carriers = forms.MultipleChoiceField(
        required=True,
        widget=forms.CheckboxSelectMultiple(attrs={
            'class':"form-check-input",
            'type':"checkbox",
            'role':"switch",}),
        choices=CARRIER_LIST,
        label= 'Carriers',)

    monthF = forms.IntegerField(
        required=True,
        min_value=1,
        max_value=12,
        widget=forms.NumberInput(
            attrs={'class':'slider','type':'range','id':'MonthFrom',}))

    monthT = forms.IntegerField(
        required=True,
        min_value=1,
        max_value=12,
        widget=forms.NumberInput(attrs={'class':'slider','type':'range','id':'MonthTo',}))
        
    year = forms.MultipleChoiceField(
        required=True,
        choices=YEARS,
        widget=forms.CheckboxSelectMultiple(attrs={
            'type':'checkbox','class':'btn-check', 'name':'yearOptions','autocomplete':'on'
        }),
    )
    

scrape/views.py
from datetime import datetime
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


from .models import MONTH_DICT, MONTH_LIST, YEARS,CARRIER_LIST
from .forms import BSfilterForm
from .main import _init_SCRAPER



class HomePageView(TemplateView):
    template_name = "base.html"

class IndexView(TemplateView):
    template_name = 'scrape/index.html'

class VesselRouteView(IndexView):
    template_name = 'scrape/vesselroute.html'



def index(request):
    return render(request, 'scrape/index.html')




def blanksailing(request):
    inital_data = {
        'monthF':datetime.now().month,
        'monthT':datetime.now().month
    }
    form = BSfilterForm(request.GET or None, initial=inital_data)
    if request.method =='POST':
        form = BSfilterForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            _init_SCRAPER(data)
            # print(data)
        else:
            print(form.errors)
    context = {
        'form':form,
        'months':MONTH_DICT
        }

    return render(request,'scrape/blanksailing.html',context)



def vesselroute(request):

    return render(request,'scrape/vesselroute.html')



def filter(request):
    form = BSfilterForm(request.POST or None)
    if form.is_valid():
        form.save()
    
    context = {'form':form}
    return render(request,'scrape/filter.html',context)


# class BlankSailingView(ListView):
#     blanksailing()
#     template_name = 'scrape/blanksailing.html'

scrape/templates/base.html
<!DOCTYPE html>
<html>
<head>
    
    <title>Maritime Logistics Tools</title>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="../static/css/style.css">
    <link rel="stylesheet" type="text/css" href="../static/css/root.css">

</head>

<style>
    #right{
        padding: 4rem 2rem;
        height: 100vh;
        background-image: url('../static/img/container-bg.jpg');
        background-size: cover;
    }

</style>

{% autoescape on %}
<body  onload="loadData()">
    <nav  role="navigation">
        <div class="nav-wrapper d-flex flex-column justify-content-around align-content-stretch"  id="menu">
            <a href="{% url 'scrape:index' %}"><span class="material-icons">directions_boat</span></a>
            <div class="list-wrapper">
                <div class="menu-list">
                    <a class="text-white text-decoration-none" href="{% url 'scrape:blanksailing' %}">BLANK SAILING</a>
                </div>
                <div class="menu-list">
                    <a class="text-white text-decoration-none" href="{% url 'scrape:vesselroute' %}">VESSEL ROUTE</a>
                </div>
            </div>
            <img src="../static/img/NM-logo-W.png" alt="" id="NM-logo">
        </div>
    </nav>
    <div class="container-fluid p-0">
        <div class="row g-0">
            <div class="col-8" id="left">
                <div class="container">
                    <h1 class="display-1">Maritime Logistics Tools</h1>
                    <hr style="width:75%;">
                    <p class="text-white-50" style="font-variant-caps: all-petite-caps;">This tool is not intended for commercial use.</p>
                   
                {% block content %}

                {% endblock %}
                </div>
                <button id="FUbutton" type="button" class="btn text-warning text-capitalize fs-6" data-bs-toggle="modal" data-bs-target="#disclaimerModal">FAIR USE DISCLAIMER</button>
            </div>
                <!--------  ---------->
            <div class="col-4" id="right">

                {% block dashboard %}

                {% endblock %}

                <div id="caption">Photo by <a href="https://unsplash.com/@aronyigin?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Aron Yigin</a> on <a href="https://unsplash.com/s/photos/shipping-container?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a></div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="disclaimerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog modal-xl">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title text-black-50" id="FairUseNotice">Fair Use Notice</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body ">
                    <h3>Fair Use</h3>
                    <br>
                    <h5>Fair Use Act Disclaimer</h5>
                    <p>This site and the content made available through this site are for educational and informational purposes only.</p>
                    <h5>Fair Use Copyright Disclaimer</h5>
                    <p>Under section 107 of the Copyright Act of 1976, allowance is made for “fair use” for purposes such as criticism, comment, news reporting, teaching, scholarship, education and research. Fair use is a use permitted by copyright statute that might otherwise be infringing.</p>
                    <h5>Fair Use Definition</h5>
                    <p>Fair use is a doctrine in United States copyright law that allows limited use of copyrighted material without requiring permission from the rights holders, such as commentary, criticism, news reporting, research, teaching or scholarship. It provides for the legal, non-licensed citation or incorporation of copyrighted material in another author’s work under a four-factor balancing test.</p>
                    <h5>Disclaimer & Fair Use Statement</h5>
                    <p>This website may contain copyrighted material, the use of which may not have been specifically authorized by the copyright owner. Some material is made available in an effort to explain issues relevant to the practice and development of trauma-informed and resilience-focused care, and/or to illustrate, transmit, and teach the use and benefits of Starr Commonwealth educational and clinical tools and methods. Some material contained in this website is distributed for research and educational purposes and for the public good.</p>
                    <br><br>
                    <p>
                        If you believe that any content or postings on this site violates your intellectual property or other rights, please notify me by email to naydeen.monzon@icloud.com
                    </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>
    
    
    
    <script type="text/javascript">
        let vh = window.innerHeight * 0.01;
        let vw = window.innerWidth * 0.01;
        document.documentElement.style.setProperty('--vh', `${vh}px`);
        document.documentElement.style.setProperty('--vw', `${vw}px`);
        window.addEventListener('resize', () => {
            let vh = window.innerHeight * 0.01;
            document.documentElement.style.setProperty('--vh', `${vh}px`);
        });
    </script>
    <script type="text/javascript">
        let MSC = document.getElementById('id_carriers_3')
        let CMA = document.getElementById('id_carriers_2')
        MSC.setAttribute('disabled','')
        CMA.setAttribute('disabled','')
    </script>
    <script type="text/javascript">
        
        var d = new Date();
        const currentMONTH = d.getMonth() 
        function loadData(){
            document.querySelectorAll('.slider').forEach((slide)=>{
                slide.setAttribute('value',currentMONTH +1)
            })
            document.querySelectorAll('.monthli').forEach((ul)=>{
                ul.children.item(currentMONTH).style.opacity = '1'
                ul.children.item(currentMONTH).style.transform  = 'scale(1.25)'
            })
        }
    </script>
    <script type="text/javascript">
        function showDate(id1, id3){
            var slide = document.getElementById(id1)
            var slideValue = slide.innerHTML = parseInt(slide.value)
            var mLIST = document.getElementById(id3).getElementsByTagName('li')
            var mLI = Object.values(mLIST)
            
            for (var obj of mLI){
                if (obj.value == slideValue){
                    obj.style.opacity = '1'
                    obj.style.transform  = 'scale(1.25)'
                }
                else{ obj.style.opacity = '.5'
                obj.style.transform  = 'scale(1)'}
            }
            slide.setAttribute('value',slideValue)
        }

    </script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
</body>
{% endautoescape %}
</html>

scrape/templates/index.html
<!DOCTYPE html>
<html>
    {% load static %}
<head>
<title>Python Getting Started on Heroku</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/css/style.css">
    <link rel="stylesheet" href="../static/css/font.css">

</head>
<body>
    <div class="container-fluid">
        <div class="row g-0">
            
            <div class="container-fluid" id="menu">
                <span class="material-icons" style="margin-bottom: 20vh;">directions_boat</span>
                <div class="menu-list">BLANK SAILING</div>
                <div class="menu-list">VESSEL ROUTE</div>
                <img src="../static/img/NM-logo-W.png" alt="" id="NM-logo">
            </div>

            <div class="col-8" id="left">
                <div class="container">
                    <h1 class="display-1">Maritime Logistics Tools</h1>
                    <hr style="width:75%;">
                    <p class="text-white-50">This tool is not intended for commercial use.</p>

                    <div class="row justify-content-around" style=" margin-top: 8vh;">
                        <div class="col-9 p-4">
                            <p ><span style="font-size: x-large;">Welcome!</span> The purpose of this tool is to gather service udpate and company development from the top leading Global Ocean Carriers for research purposes.</p>
                        </div>
                        <div class="col-3">
                            <div class="d-block p-4">
                                <h5>Tools:</h5>
                                <ul>
                                    <li>Python</li>
                                    <li>Heroku</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    
                    
                </div>
                <button id="FUbutton" type="button" class="btn text-warning text-capitalize fs-6" data-bs-toggle="modal" data-bs-target="#disclaimerModal">FAIR USE DISCLAIMER</button>
            </div>


            <div class="col-4" id="right">
                <img src="../static/img/container-bg.jpg" alt="" class="bg">
                <div id="caption">
                    <caption>Photo by <a href="https://unsplash.com/@aronyigin?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Aron Yigin</a> on <a href="https://unsplash.com/s/photos/shipping-container?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
                    </caption>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="disclaimerModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title text-black-50" id="FairUseNotice">Fair Use Notice</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                    <h3>Fair Use</h3>
                    <br>
                    <h5>Fair Use Act Disclaimer</h5>
                    <p>This site and the content made available through this site are for educational and informational purposes only.</p>
                    <h5>Fair Use Copyright Disclaimer</h5>
                    <p>Under section 107 of the Copyright Act of 1976, allowance is made for “fair use” for purposes such as criticism, comment, news reporting, teaching, scholarship, education and research. Fair use is a use permitted by copyright statute that might otherwise be infringing.</p>
                    <h5>Fair Use Definition</h5>
                    <p>Fair use is a doctrine in United States copyright law that allows limited use of copyrighted material without requiring permission from the rights holders, such as commentary, criticism, news reporting, research, teaching or scholarship. It provides for the legal, non-licensed citation or incorporation of copyrighted material in another author’s work under a four-factor balancing test.</p>
                    <h5>Disclaimer & Fair Use Statement</h5>
                    <p>This website may contain copyrighted material, the use of which may not have been specifically authorized by the copyright owner. Some material is made available in an effort to explain issues relevant to the practice and development of trauma-informed and resilience-focused care, and/or to illustrate, transmit, and teach the use and benefits of Starr Commonwealth educational and clinical tools and methods. Some material contained in this website is distributed for research and educational purposes and for the public good.</p>
                    <br><br>
                    <p>
                        If you believe that any content or postings on this site violates your intellectual property or other rights, please notify me by email to naydeen.monzon@icloud.com
                    </p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

scrape/templates/scrape/blanksailing.html
{% extends "base.html" %}



{% block content %}
{% load static %}
    <div class="container " style=" margin-top: 2vh;">

    </div>
{% endblock %}

{% block dashboard %}

    <div id="dashboard" class="container-fluid p-5 justify-content-around align-content-stretch align-items-stretch">
        
        <form action="." class="d-flex flex-column gap-4 py-2" method="post">
            {% csrf_token %}
            
            <div class="row text-start align-items-stretch justify-content-evenly">

                <div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
                    <div class="d-flex gap-5 justify-content-around for">
                        {% for item in form.carriers %}
                            {% if 'hlc' == item.data.value %}
                            <div class="form-switch">
                                <input class="form-check-input" name='carriers' type="checkbox" role="switch" id="{{item.data.attrs.id}}" value="{{item.data.value}}" checked>
                                <label class="form-check-label" for="{{item.data.attrs.id}}">{{item.data.label}}</label>
                            </div>
                            {% elif item.data.value == 'msc' or item.data.value == 'maeu' %}
                            <div class="form-switch">
                                <input class="form-check-input" name='carriers' type="checkbox" role="switch" id="{{item.data.attrs.id}}" value="{{item.data.value}}"  disabled>
                                <label class="form-check-label" for="{{item.data.attrs.id}}">{{item.data.label}}</label>
                            </div>
                            {% else %}
                            <div class="form-switch">
                                <input class="form-check-input" name='carriers' type="checkbox" role="switch" id="{{item.data.attrs.id}}" value="{{item.data.value}}" >
                                <label class="form-check-label" for="{{item.data.attrs.id}}">{{item.data.label}}</label>
                            </div>
                            {% endif %}
                        {% endfor %}

                    </div>
                </div>
            </div>
            <div>
                <hr>
                <legend class="text-white-75 p-0" style="font-variant-caps: all-petite-caps;font-size:1rem;color: #d37800;">Select date range</legend>
            </div>
            <div class="row text-center justify-content-evenly">
                <div class="col-6 date-range">
                    <fieldset oninput="showDate('MonthFrom','monthFROMlist')">
                        <div class="container-fluid ">
                            <label class="row">From</label>
                            <div class="row">
                                <div class="col-6">
                                    <ul id="monthFROMlist" class="p-0 m-0 monthli" name="month">
                                        {% for key, value in months.items %}
                                        <li value="{{key}}" label={{value}}>{{value}}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="col-6">
                                    {{form.monthF}}
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-6 date-range">
                    <fieldset oninput="showDate('MonthTo','monthTOlist')">
                        <div class="container-fluid ">
                            <label class="row">To</label>
                            <div class="row">
                                <div class="col-6">
                                    <ul id="monthTOlist" class="p-0 m-0 monthli" name="month">
                                    {% for key, value in months.items %}
                                    <li value="{{key}}" label={{value}}>{{value}}</li>
                                    {% endfor %}
                                    </ul>
                                </div>
                                <div class="col-6">
                                    {{form.monthT}}
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="row justify-content-evenly text-center w-75 my-4 pt-4" id="year">
                    <div class=" btn-group btn-group-toggle" data-toggle="buttons checkbox">
                        {% for item in form.year %}
                            {% if '2021' == item.data.label %}
                                <input type="checkbox" class="btn-check" name="year" value='{{item.data.value}}' id="{{item.data.attrs.id}}" autocomplete="on" checked>
                                <label class="btn btn-outline-warning fw-bold" for='{{item.data.attrs.id}}'>{{item.data.value}}</label>
                            {% else %}
                                <input type="checkbox" class="btn-check" name="year" value='{{item.data.value}}' id="{{item.data.attrs.id}}" autocomplete="on">
                                <label class="btn btn-outline-warning fw-bold" for='{{item.data.attrs.id}}'>{{item.data.value}}</label>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
            <hr>
            <div id="dashboard-submit" tabindex="1">

                <input type="submit" value="SUBMIT"  role="button">
                <div id="submit-bg"><i class="bi bi-chevron-double-right" style="font-size: 2rem; cursor: pointer;"></i></div>
                
            </div>

            <div id='dashboard-bg'></div>
        </form>
        
    </div>
 {% endblock %}

                            

scrape/templates/scrape/filter.html
{% extends "base.html" %}


{% block content %}
{% load static %}
<div class="container" style=" margin-top: 2vh;">

</div>
{% endblock %}


{% block dashboard %}
{% load static %}

 {% endblock %}

scrape/templates/scrape/index.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="row justify-content-around" style=" margin-top: 8vh;">
    <div class="col-9 p-4">
        <p ><span style="font-size: x-large;">Welcome!</span> The purpose of this tool is to gather service udpate and company development from the top leading Global Ocean Carriers for research purposes.</p>
    </div>
    <div class="col-3">
        <div class="d-block p-4">
            <h5>Tools:</h5>
            <ul>
                <li>Python</li>
                <li>Heroku</li>
                
            </ul>
        </div>
    </div>
</div>
{% endblock %}
                

scrape/templates/scrape/vesselroute.html
{% extends "base.html" %}
{% load static %}




{% block content %}





{% endblock %}